FROM registry.fedoraproject.org/fedora:latest@sha256:2a1174004a176f493f721eb83971c86657d2007a8bb90ba36c3d677d3e4e8ae6

COPY mock-wrapper /usr/bin

RUN dnf install -y mock rpmdevtools rpkg copr-cli rpmlint && dnf clean all

ENTRYPOINT ["/usr/bin/mock-wrapper"]
